{
  "login": "TJRoss23",
  "id": 7781713,
  "avatar_url": "https://avatars.githubusercontent.com/u/7781713?",
  "gravatar_id": "615f93e0c60456b6c0ed64ea63434fa2",
  "url": "https://api.github.com/users/TJRoss23",
  "html_url": "https://github.com/TJRoss23",
  "followers_url": "https://api.github.com/users/TJRoss23/followers",
  "following_url": "https://api.github.com/users/TJRoss23/following{/other_user}",
  "gists_url": "https://api.github.com/users/TJRoss23/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/TJRoss23/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/TJRoss23/subscriptions",
  "organizations_url": "https://api.github.com/users/TJRoss23/orgs",
  "repos_url": "https://api.github.com/users/TJRoss23/repos",
  "events_url": "https://api.github.com/users/TJRoss23/events{/privacy}",
  "received_events_url": "https://api.github.com/users/TJRoss23/received_events",
  "type": "User",
  "site_admin": false,
  "public_repos": 18,
  "public_gists": 0,
  "followers": 1,
  "following": 0,
  "created_at": "2014-06-03T14:07:07Z",
  "updated_at": "2014-06-20T11:48:57Z"
}